#spring.boot.admin.url=http://localhost:8788
#server.port=8001
#management.endpoints.web.exposure.include="*"


spring.boot.admin.client.url: "http://localhost:8788"
management.endpoints.web.exposure.include: "*"